# Generated by Django 2.2.4 on 2019-08-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_box_v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='recipe_box_v1.Author'),
        ),
    ]
