# Generated by Django 2.2.3 on 2019-07-31 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_box_v1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
    ]
