# Generated by Django 2.2.3 on 2019-09-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_box_v1', '0002_recipe_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites', to='recipe_box_v1.Recipe'),
        ),
    ]
